In [8]:
import numpy as np

# 1

**Crear un arreglo de 5 elementos enteros, todos iguales a 10**

In [9]:
np.full((5),10)

array([10, 10, 10, 10, 10])

# 2

**Crear una matriz 2x3 con todos los elementos iguales a 5**

In [10]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

# 3

**Crear un arreglo multidimensional aleatorio de 3 tensores, cada uno de 2 filas y 3 columnas**

In [68]:
np.random.rand(3,2,3)

array([[[0.27499551, 0.27787874, 0.92891673],
        [0.26427586, 0.63491385, 0.71936437]],

       [[0.66898812, 0.41272379, 0.97771034],
        [0.22862169, 0.25070395, 0.16340178]],

       [[0.08110583, 0.06963316, 0.43093661],
        [0.77524109, 0.61152553, 0.56888192]]])

# 4

**Dados los siguientes arreglos:
arr1 = np.array([1, 2, 3, 4, 5]) 
arr2 = np.array([6, 7, 8, 9, 10])
Sumar, restar y multiplicar.**


In [24]:
arr1 = np.array([1, 2, 3, 4, 5]) 
arr2 = np.array([6, 7, 8, 9, 10])

In [25]:
# Suma
print(arr1+arr2)

[ 7  9 11 13 15]


In [26]:
# Resta
print(arr1-arr2)

[-5 -5 -5 -5 -5]


In [27]:
# Multiplicación
print(arr1*arr2)

[ 6 14 24 36 50]


# 5

**Dado el siguiente arreglo:
data = np.array([23, 17, 25, 30, 21, 29, 18])
Calcular la media y la desviación estándar**


array1 = np.array([23, 17, 25, 30, 21, 29, 18])

In [38]:
# Media
media = np.mean(array1)
print("Media:", media)

Media: 23.285714285714285


In [39]:
# Desviación estándar
desviacion_estandar = np.std(array1)
print("Desviación estándar:", desviacion_estandar)

Desviación estándar: 4.681705602335411


# 6

**Dado el siguiente arreglo:
datos = np.array([12, 15, 8, 10, 5, 14, 9, 7])
Crear un nuevo arreglo que contenga los elementos mayores o iguales a 10**


In [36]:
datos = np.array([12, 15, 8, 10, 5, 14, 9, 7])

nuevo_arreglo = datos[datos >= 10]
print(nuevo_arreglo)

[12 15 10 14]


# 7

**7.	Dado el siguiente arreglo: 
data = np.array([[12, 15, 20, 25], [8, 10, 12, 14], [18, 20, 22, 24]])**

data = np.array([[12, 15, 20, 25], [8, 10, 12, 14], [18, 20, 22, 24]])

7.1 Mostrar el numero por pantalla el numero 24

In [64]:
data[2,3]

24

7.2	Mostrar la fila 3: [18,20,22,24]

In [65]:
data[2]

array([18, 20, 22, 24])

7.3	Mostrar la columna 2: [15,10,20].

In [66]:
data[:, 1]

array([15, 10, 20])

# 8

**Dado el siguiente arreglo multidimensional:
arregloMultiD = np.random.rand(4,8,4)**

arregloMultiD = np.random.rand(4,8,4)

8.1	Volverlo de manera lineal

In [71]:
arregloMultiD = np.random.rand(4, 8, 4)

arrayLineal = arregloMultiD.reshape(-1)

print(arrayLineal)

[0.70481696 0.20382876 0.11948846 0.8883125  0.64144797 0.98840291
 0.39779723 0.7650947  0.0650955  0.00362895 0.55326662 0.48579025
 0.23088876 0.6485927  0.7054639  0.48140124 0.99251373 0.57107458
 0.21010855 0.28148096 0.48268683 0.67101064 0.59006028 0.24571744
 0.13368844 0.82077435 0.48659827 0.96565558 0.53382061 0.91054532
 0.13552647 0.10388608 0.99041984 0.22112547 0.34388465 0.79846964
 0.24565856 0.63560324 0.61916028 0.93108534 0.1863849  0.15104188
 0.73738888 0.59178576 0.96359021 0.6931936  0.78395828 0.27274377
 0.12927791 0.8628181  0.95499617 0.07903567 0.61431581 0.96195929
 0.93165515 0.40975171 0.15833139 0.63629563 0.12183967 0.25118887
 0.20743813 0.57395841 0.78168912 0.03349956 0.44855701 0.01827621
 0.03441544 0.98620804 0.33618959 0.0492575  0.75161648 0.04993093
 0.06736359 0.27844005 0.38011569 0.42554991 0.92905155 0.81993081
 0.00288564 0.26206174 0.48712122 0.28664324 0.6436178  0.69915582
 0.94344897 0.71873611 0.19295246 0.97653893 0.39708597 0.9322

8.2	Reajustarlo en tuplas

In [75]:
arrayAjustado = arregloMultiD.reshape(-1,2)

print(arrayAjustado)

[[0.11937845 0.38776296]
 [0.24487655 0.61195519]
 [0.65992695 0.37933621]
 [0.96122898 0.52033739]
 [0.60357822 0.34517858]
 [0.12211619 0.96252009]
 [0.56244366 0.09180187]
 [0.90961529 0.22435924]
 [0.80985909 0.93323479]
 [0.72183298 0.83867263]
 [0.78164936 0.11965864]
 [0.00652272 0.55983778]
 [0.65485758 0.98932895]
 [0.3006246  0.23240986]
 [0.24544578 0.15628041]
 [0.94502119 0.43850852]
 [0.95411293 0.24247052]
 [0.06728776 0.73719695]
 [0.86514781 0.41919054]
 [0.94410525 0.06211039]
 [0.20111468 0.70016565]
 [0.25649448 0.59309027]
 [0.47756923 0.45161304]
 [0.55924787 0.81051002]
 [0.75271363 0.56937126]
 [0.90767617 0.23301735]
 [0.87659498 0.66932562]
 [0.47568749 0.57088974]
 [0.4070008  0.88226189]
 [0.94177807 0.21064232]
 [0.13807818 0.97425505]
 [0.56528738 0.36444174]
 [0.03680419 0.6252541 ]
 [0.25888934 0.80646071]
 [0.07644546 0.45993015]
 [0.22842215 0.0350528 ]
 [0.76563555 0.92180496]
 [0.35313029 0.62810009]
 [0.79503143 0.34056849]
 [0.2842129  0.1168459 ]
